ControleEstoque.Web/Controllers/Cadastro/CadProdutoController.cs
using AutoMapper;
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers
{
    [Authorize(Roles = "Gerente,Administrativo,Operador")]
    public class CadProdutoController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index()
        {
            ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
            ViewBag.QuantMaxLinhasPorPagina = _quantMaxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = Mapper.Map<List<ProdutoViewModel>>(ProdutoModel.RecuperarLista(ViewBag.PaginaAtual, _quantMaxLinhasPorPagina));
            var quant = ProdutoModel.RecuperarQuantidade();

            var difQuantPaginas = (quant % ViewBag.QuantMaxLinhasPorPagina) > 0 ? 1 : 0;
            ViewBag.QuantPaginas = (quant / ViewBag.QuantMaxLinhasPorPagina) + difQuantPaginas;
            ViewBag.UnidadesMedida = Mapper.Map<List<UnidadeMedidaViewModel>>(UnidadeMedidaModel.RecuperarLista(1, 9999));
            ViewBag.Grupos = Mapper.Map<List<GrupoProdutoViewModel>>(GrupoProdutoModel.RecuperarLista(1, 9999));
            ViewBag.Marcas = Mapper.Map<List<MarcaProdutoViewModel>>(MarcaProdutoModel.RecuperarLista(1, 9999));
            ViewBag.Fornecedores = Mapper.Map<List<FornecedorViewModel>>(FornecedorModel.RecuperarLista());
            ViewBag.LocaisArmazenamento = Mapper.Map<List<LocalArmazenamentoViewModel>>(LocalArmazenamentoModel.RecuperarLista(1, 9999));

            return View(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ProdutoPagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = Mapper.Map<List<ProdutoViewModel>>(ProdutoModel.RecuperarLista(pagina, tamPag, filtro, ordem));

            return Json(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarProduto(int id)
        {
            var vm = Mapper.Map<ProdutoViewModel>(ProdutoModel.RecuperarPeloId(id));

            return Json(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarQuantidadeEstoqueProduto(int id)
        {
            var model = ProdutoModel.RecuperarPeloId(id);
            if (model != null)
            {
                return Json(new { OK = true, Result = model.QuantEstoque });
            }
            else
            {
                return Json(new { OK = false });
            }
        }

        [HttpPost]
        [Authorize(Roles = "Gerente,Administrativo")]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirProduto(int id)
        {
            return Json(ProdutoModel.ExcluirPeloId(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarProduto()
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            var nomeArquivoImagem = "";
            HttpPostedFileBase arquivo = null;
            if (Request.Files.Count > 0)
            {
                arquivo = Request.Files[0];
                nomeArquivoImagem = Guid.NewGuid().ToString() + ".jpg";
            }

            var model = new ProdutoModel()
            {
                Id = Int32.Parse(Request.Form["Id"]),
                Codigo = Request.Form["Codigo"],
                Nome = Request.Form["Nome"],
                PrecoCusto = Decimal.Parse(Request.Form["PrecoCusto"]),
                PrecoVenda = Decimal.Parse(Request.Form["PrecoVenda"]),
                QuantEstoque = Int32.Parse(Request.Form["QuantEstoque"]),
                IdUnidadeMedida = Int32.Parse(Request.Form["IdUnidadeMedida"]),
                IdGrupo = Int32.Parse(Request.Form["IdGrupo"]),
                IdMarca = Int32.Parse(Request.Form["IdMarca"]),
                IdFornecedor = Int32.Parse(Request.Form["IdFornecedor"]),
                IdLocalArmazenamento = Int32.Parse(Request.Form["IdLocalArmazenamento"]),
                Ativo = (Request.Form["Ativo"] == "true"),
                Imagem = nomeArquivoImagem
            };

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    var nomeArquivoImagemAnterior = "";
                    if (model.Id > 0)
                    {
                        nomeArquivoImagemAnterior = ProdutoModel.RecuperarImagemPeloId(model.Id);
                    }

                    var id = model.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                        if (!string.IsNullOrEmpty(nomeArquivoImagem) && arquivo != null)
                        {
                            var diretorio = Server.MapPath("~/Content/Imagens");

                            var caminhoArquivo = Path.Combine(diretorio, nomeArquivoImagem);
                            arquivo.SaveAs(caminhoArquivo);

                            if (!string.IsNullOrEmpty(nomeArquivoImagemAnterior))
                            {
                                var caminhoArquivoAnterior = Path.Combine(diretorio, nomeArquivoImagemAnterior);
                                System.IO.File.Delete(caminhoArquivoAnterior);
                            }
                        }
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

ControleEstoque.Web/Views/CadProduto/Index.cshtml
@model List<ControleEstoque.Web.Models.ProdutoViewModel>
@{
    Layout = "~/Views/Shared/_Cadastro.cshtml";
    ViewBag.Title = "Produtos";
    ViewBag.Lista = Model;
}

@section Styles {
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Content/Cadastro/Produto.css" rel="stylesheet" />
    <style>
        .dialogo > .modal-dialog {
            width: 700px !important;
        }
    </style>
}

@section TituloGrid {
    <th><span class="coluna-ordenacao" data-campo="codigo">Código</span></th>
    <th><span class="coluna-ordenacao" data-campo="nome">Nome</span></th>
    <th><span class="coluna-ordenacao" data-campo="quant_estoque">Quantidade</span></th>
    <th><span class="coluna-ordenacao" data-campo="ativo">Ativo</span></th>
    <th>Ação</th>
}

@section CamposCadastro {
    <div class="row">
        <div class="col-md-4">
            @Html.Label("txt_codigo", "Código", new { @class = "control-label" })
            @Html.TextBox("txt_codigo", null, new { @class = "form-control" })
        </div>
        <div class="col-md-8">
            @Html.Label("txt_nome", "Nome", new { @class = "control-label" })
            @Html.TextBox("txt_nome", null, new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            @Html.Label("txt_preco_custo", "Preço de Custo", new { @class = "control-label" })
            @Html.TextBox("txt_preco_custo", null, new { @class = "form-control" })
        </div>
        <div class="col-md-4">
            @Html.Label("txt_preco_venda", "Preço de Venda", new { @class = "control-label" })
            @Html.TextBox("txt_preco_venda", null, new { @class = "form-control" })
        </div>
        <div class="col-md-4">
            @Html.Label("txt_quant_estoque", "Quant Estoque", new { @class = "control-label", type = "number" })
            @Html.TextBox("txt_quant_estoque", null, new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            @Html.Label("ddl_unidade_medida", "Unidade de Medida", new { @class = "control-label" })
            @Html.DropDownList("ddl_unidade_medida", new SelectList(ViewBag.UnidadesMedida, "Id", "Nome"), new { @class = "form-control" })
        </div>
        <div class="col-md-8">
            @Html.Label("ddl_grupo", "Grupo", new { @class = "control-label" })
            @Html.DropDownList("ddl_grupo", new SelectList(ViewBag.Grupos, "Id", "Nome"), new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            @Html.Label("ddl_marca", "Marca", new { @class = "control-label" })
            @Html.DropDownList("ddl_marca", new SelectList(ViewBag.Marcas, "Id", "Nome"), new { @class = "form-control" })
        </div>
        <div class="col-md-8">
            @Html.Label("ddl_fornecedor", "Fornecedor", new { @class = "control-label" })
            @Html.DropDownList("ddl_fornecedor", new SelectList(ViewBag.Fornecedores, "Id", "Nome"), new { @class = "form-control" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            @Html.Label("ddl_local_armazenamento", "Local Armazenamento", new { @class = "control-label" })
            @Html.DropDownList("ddl_local_armazenamento", new SelectList(ViewBag.LocaisArmazenamento, "Id", "Nome"), new { @class = "form-control" })
        </div>
        <div class="col-md-8">
            <div class="form-check" style="line-height: 6em; margin-bottom: -2em">
                @Html.CheckBox("cbx_ativo", new { @class = "form-check-input" })
                @Html.Label("cbx_ativo", "Ativo", new { @class = "form-check-label" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.Label("txt_imagem", "Imagem", new { @class = "control-label" })
            @Html.TextBox("txt_imagem", null, new { @class = "form-control", type = "file", accept = "image/jpg,image/jpeg" })
        </div>
    </div>

    <div id="modal_imagem" class="invisivel" role="dialog"></div>
}

@section Scripts{
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script src="~/Scripts/jquery.mask.min.js"></script>
    <script>
        var tituloPagina = '@ViewBag.Title';
        var url_excluir = '@Url.Action("ExcluirProduto", "CadProduto")';
        var url_confirmar = '@Url.Action("SalvarProduto", "CadProduto")';
        var url_page_click = '@Url.Action("ProdutoPagina", "CadProduto")';
        var url_tam_pag_change = '@Url.Action("ProdutoPagina", "CadProduto")';
        var url_filtro_change = '@Url.Action("ProdutoPagina", "CadProduto")';
        var url_alterar = '@Url.Action("RecuperarProduto", "CadProduto")';
        var linhas = [];

        @{
            var linha = 0;
            foreach (var item in Model)
            {
                linha++;
                if (linha <= ViewBag.QuantMaxLinhasPorPagina)
                {
                    @:linhas.push(@Html.Raw(Json.Encode(item)));
                                                                }
                else
                {
                    break;
                }
            }
        }
    </script>
    <script id="template-grid" type="x-tmpl-mustache">
        <tr data-id="{{ Id }}" data-imagem="{{ Imagem }}">
            <td>{{ Codigo }}</td>
            <td>{{ Nome }}</td>
            <td>{{ QuantEstoque }}</td>
            <td>{{ #Ativo }}SIM{{ /Ativo }}{{ ^Ativo }}NÃO{{ /Ativo }}</td>
            <td>
                <a class="btn btn-default btn-exibir-imagem" role="button"><i class="glyphicon glyphicon-picture"></i></a>
                <a class="btn btn-primary btn-alterar" role="button"><i class="glyphicon glyphicon-pencil"></i> Alterar</a>
                <a class="btn btn-danger btn-excluir" role="button"><i class="glyphicon glyphicon-trash"></i> Excluir</a>
            </td>
        </tr>
    </script>
    <script id="template-imagem" type="x-tmpl-mustache">
        <fieldset>
            <div class="row">
                <div class="col-md-12">
                    <img src="/Content/Imagens/{{ Imagem }}" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="modal-footer">
                            <a id="btn_sair_imagem" class="btn btn-default" role="button" data-dismiss="modal">
                                <i class="glyphicon glyphicon-remove"></i> Sair
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </script>
    <script src="~/Scripts/Cadastro/Produto.js"></script>
}