ControleEstoque.Web/Controllers/Cadastro/CadPerfilController.cs
using AutoMapper;
using ControleEstoque.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleEstoque.Web.Controllers.Cadastro
{
    [Authorize(Roles = "Gerente")]
    public class CadPerfilController : Controller
    {
        private const int _quantMaxLinhasPorPagina = 5;

        public ActionResult Index()
        {
            ViewBag.ListaUsuario = Mapper.Map<List<UsuarioViewModel>>(UsuarioModel.RecuperarLista());
            ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina);
            ViewBag.QuantMaxLinhasPorPagina = _quantMaxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = Mapper.Map<List<PerfilViewModel>>(PerfilModel.RecuperarLista(ViewBag.PaginaAtual, _quantMaxLinhasPorPagina));
            var quant = PerfilModel.RecuperarQuantidade();

            var difQuantPaginas = (quant % ViewBag.QuantMaxLinhasPorPagina) > 0 ? 1 : 0;
            ViewBag.QuantPaginas = (quant / ViewBag.QuantMaxLinhasPorPagina) + difQuantPaginas;

            return View(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult PerfilPagina(int pagina, int tamPag, string filtro, string ordem)
        {
            var lista = Mapper.Map<List<PerfilViewModel>>(PerfilModel.RecuperarLista(pagina, tamPag, filtro, ordem));

            return Json(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RecuperarPerfil(int id)
        {
            var ret = Mapper.Map<PerfilViewModel>(PerfilModel.RecuperarPeloId(id));
            return Json(ret);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ExcluirPerfil(int id)
        {
            return Json(PerfilModel.ExcluirPeloId(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult SalvarPerfil(PerfilViewModel model, List<int> idUsuarios)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                model.Usuarios = new List<UsuarioViewModel>();
                if (idUsuarios == null || idUsuarios.Count == 0)
                {
                    model.Usuarios.Add(new UsuarioViewModel() { Id = -1 });
                }
                else
                {
                    foreach (var id in idUsuarios)
                    {
                        model.Usuarios.Add(new UsuarioViewModel() { Id = id });
                    }
                }

                try
                {
                    var vm = Mapper.Map<PerfilModel>(model);
                    var id = vm.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
    }
}

ControleEstoque.Web/Views/CadPerfil/Index.cshtml
@model List<ControleEstoque.Web.Models.PerfilViewModel>
@{
    Layout = "~/Views/Shared/_Cadastro.cshtml";
    ViewBag.Title = "Perfis de Usuários";
    ViewBag.Lista = Model;
}

@section Styles {
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Content/Cadastro/Perfil.css" rel="stylesheet" />
}

@section TituloGrid {
    <th><span class="coluna-ordenacao" data-campo="nome">Nome</span></th>
    <th><span class="coluna-ordenacao" data-campo="ativo">Ativo</span></th>
    <th>Ação</th>
}

@section CamposCadastro {
    <div class="row">
        <div class="col-md-12">
            @Html.Label("txt_nome", "Nome", new { @class = "control-label" })
            @Html.TextBox("txt_nome", null, new { @class = "form-control" })
        </div>
    </div>
    <div class="row" style="margin-top: 15px">
        <div class="col-md-12">
            <div class="form-check">
                @Html.CheckBox("cbx_ativo", new { @class = "form-check-input" })
                @Html.Label("cbx_ativo", "Ativo", new { @class = "form-check-label" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group" style="margin: 0 10px 0 10px">
            <div class="col-md-12">
                <h4 class="text-center">Usuários</h4>
                <div class="well" style="max-height: 300px; padding: 5px; margin: 0; overflow: auto">
                    <ul id="lista_usuario" class="list-group checked-list-box" style="margin-bottom: 0">
                        @foreach (var usuario in (List<ControleEstoque.Web.Models.UsuarioViewModel>)ViewBag.ListaUsuario)
                        {
                            <li class="list-group-item">
                                <label style="margin-bottom: 0">
                                    <input type="checkbox" data-id-usuario="@usuario.Id" /> @usuario.Nome
                                </label>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts{
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script>
        var tituloPagina = '@ViewBag.Title';
        var url_excluir = '@Url.Action("ExcluirPerfil", "CadPerfil")';
        var url_confirmar = '@Url.Action("SalvarPerfil", "CadPerfil")';
        var url_page_click = '@Url.Action("PerfilPagina", "CadPerfil")';
        var url_tam_pag_change = '@Url.Action("PerfilPagina", "CadPerfil")';
        var url_filtro_change = '@Url.Action("PerfilPagina", "CadPerfil")';
        var url_alterar = '@Url.Action("RecuperarPerfil", "CadPerfil")';
        var linhas = [];

        @{
            var linha = 0;
            foreach (var item in Model)
            {
                linha++;
                if (linha <= ViewBag.QuantMaxLinhasPorPagina)
                {
                    @:linhas.push(@Html.Raw(Json.Encode(item)));
                                                                }
                else
                {
                    break;
                }
            }
        }
    </script>
    <script id="template-grid" type="x-tmpl-mustache">
        <tr data-id="{{ Id }}">
            <td>{{ Nome }}</td>
            <td>{{ #Ativo }}SIM{{ /Ativo }}{{ ^Ativo }}NÃO{{ /Ativo }}</td>
            <td>
                <a class="btn btn-primary btn-alterar" role="button"><i class="glyphicon glyphicon-pencil"></i> Alterar</a>
                <a class="btn btn-danger btn-excluir" role="button"><i class="glyphicon glyphicon-trash"></i> Excluir</a>
            </td>
        </tr>
    </script>
    <script src="~/Scripts/Cadastro/Perfil.js"></script>
}